Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  LayerName:
    class_relu5:
      Precision:
        result: ap_ufixed<5,0>
      ReuseFactor: 1
    classifier_out:
      Precision:
        bias: ap_fixed<16,7>
        weight: ap_fixed<16,7>
      ReuseFactor: 1
    classifier_output:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      exp_table_t: ap_fixed<18,8>
      inv_table_t: ap_fixed<18,4>
      table_size: 1024
    decoder_output:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
    encoder_input:
      Precision:
        result: ap_fixed<16,6>
    encoder_output:
      Precision:
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
    encoder_output_relu:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    fc1:
      Precision:
        bias: ap_fixed<4,1>
        weight: ap_fixed<4,1>
      ReuseFactor: 1
    fc2_prun:
      Precision:
        bias: ap_fixed<4,1>
        weight: ap_fixed<4,1>
      ReuseFactor: 1
    fc3:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
    fc4:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
    fc4_prunedclass:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
    fc5_class:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
    prunclass_relu4:
      Precision:
        result: ap_ufixed<5,0>
      ReuseFactor: 1
    relu1:
      Precision:
        result: ap_ufixed<4,0>
      ReuseFactor: 1
    relu2:
      Precision:
        result: ap_ufixed<4,0>
      ReuseFactor: 1
    relu3:
      Precision:
        result: ap_ufixed<5,0>
      ReuseFactor: 1
    relu4:
      Precision:
        result: ap_ufixed<5,0>
      ReuseFactor: 1
    sigmoid:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model/AE_model/hls4ml_prj/keras_model.h5'
OutputDir: model/AE_model/hls4ml_prj
OutputPredictions: null
ProjectName: myproject
Stamp: 3faBA35B
XilinxPart: xc250-figd2104-2L-e
