Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_1/hls4ml_prj/keras_model.h5'
OutputDir: model_1/hls4ml_prj
OutputPredictions: null
ProjectName: myproject
Stamp: 3D7f2580
XilinxPart: xcu250-figd2104-2L-e
